version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pr7
    ports:
      - "5433:5432"

  redis:
    image: redis
    ports:
      - 6379:6379

  authservice:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8082:8087"
    depends_on:
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pr7
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    links:
      - "redis"

  app:
    build:
      context: ./pr5
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pr7
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password